import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import AppRedirect from '@/components/AppRedirect/page';
import Footer from '@/components/Footer/page';
import MainHeader from '@/components/MainHeader/page';
import { Toaster } from '@/components/ui/sonner';
import AppProvide from '@/redux/provider';

import './globals.css';

const roboto = Roboto({
    weight: ['400', '500', '700', '900'],
    style: ['normal', 'italic'],
    subsets: ['greek']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <AppProvide>
                    <AppRedirect>
                        <MainHeader />
                        {children}
                        <Footer />
                        <Toaster />
                    </AppRedirect>
                </AppProvide>
            </body>
        </html>
    );
}
